#!/bin/bash

#Forge Server Mod Installer

#GPL-3.0 LICENSE Copyright MysteryManYT-ttv 2026

#If you had just ran the Forge Server setup script that goes with
#script then youshould be fine.
#If you do not have the Forge server installer script, download it here!
https://github.com/MysteryManYT-ttv/All-Bash-Scripts-by-MysteryManYT-ttv

GREEN=$'\033[1;32m'
ENDCOLOR=$'\033[1;33m'

echo ${GREEN} "Installing Forge Server mods" ${ENDCOLOR}

wget -O ~/Downloads/physics-mod-3.0.20-mc-1.20.1-forge.jar \
"https://cdn.modrinth.com/data/Xy8aRQKS/versions/binwAk5d/physics-mod-3.0.20-mc-1.20.1-forge.jar?mr_download_reason=standalone"

wget -O ~/Downloads/automodpack-mc1.20.1-forge-4.0.6.jar \
"https://cdn.modrinth.com/data/k68glP2e/versions/MJclhoqa/automodpack-mc1.20.1-forge-4.0.6.jar?mr_download_reason=standalone"

wget -O ~/Downloads/oreexcavation-1.13.174.jar \
"https://www.curseforge.com/api/v1/mods/250898/files/5754631/download"

wget -O ~/Downloads/TheOneWhoWatches-V1.4.4-1.20.1.jar \
"https://www.curseforge.com/api/v1/mods/940557/files/7608035/download"

mv ~/Downloads/physics-mod-3.0.20-mc-1.20.1-forge.jar ~/Documents/Minecraft-Server/mods
mv ~/Downloads/automodpack-mc1.20.1-forge-4.0.6.jar ~/Documents/Minecraft-Server/mods
mv ~/Downloads/oreexcavation-1.13.174.jar ~/Documents/Minecraft-Server/mods
mv ~/Downloads/TheOneWhoWatches-V1.4.4-1.20.1.jar ~/Documents/Minecraft-Server/mods

cd ~/Documents/Minecraft-Server/ 
sudo bash ~/Documents/Minecraft-Server/run.sh

